name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy using SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          if [ ! -d "/production/github/clone/.git" ]; then
            git clone git@github.com:yourusername/yourrepository.git /production/github/clone
          fi
          cd /production/github/clone
          git pull origin main
          if [ -f "package.json" ]; then
            npm install --only=prod
            npm run build
          else
            echo "package.json not found!"
            exit 1