name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy using SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          # Ensure the target directory exists
          mkdir -p /production/github/clone

          # Navigate to the target directory
          cd /production/github/clone

          # Check if the directory is a Git repository
          if [ ! -d ".git" ]; then
            git clone git@github.com:ceo-py/react-github-action.git .
          else
            git pull origin main
          fi

          # Navigate to the repository directory
          cd /production/github/clone

          # Check for package.json and run build process
          if [ -f "package.json" ]; then
            npm install --only=prod
            npm run build
          else
            echo "package.json not found!"
            exit 1
